services:
  bot:
    image: python:3.12-slim
    container_name: vpn_tg_bot
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    command: bash -c "pip install -r requirements.txt && python -m bot.main"
